# docker-compose.yml for Enhanced Trading Bot (Pro Signal Logic v2)
# Version: 2.0
# This version includes price action, candlestick, and indicator confirmation logic

version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-botv2
    labels:
      - "bot.version=2.0"
      - "bot.description=Enhanced with Pro Signal Logic (v2): Price Action + Indicator Confirmation"
    volumes:
      - ./data:/app/data
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    # Add any environment variables your bot needs